### ISSUE TITLE
Eseményekhez tartozó presetek

### ISSUE THREAD

**Issue by gutasiadam** [gutasiadam/mediaio#112]
A takeout oldalon lehessen események közül választani, amelyekre kattintva kiválasztja az oldal azomkat a bennlèvő tárgyakat, amiket vinni szoktunk rá

- Ha van olyan tárgy, ami nincs benn, de az eseményhez tartozik, azt is jelezze valamilyen formában. (felugró ablak)

**Comment by foldesa** [comment]
már csak ez van "Ha van olyan tárgy, ami nincs benn, de az eseményhez tartozik, azt is jelezze valamilyen formában. (felugró ablak)"
