### ISSUE TITLE
Pathfinder átírása

### ISSUE THREAD

**Issue by gutasiadam** [gutasiadam/mediaio#143]
Írjuk át táblázatos formába a Pathfindert, olyanra mint az _Adatok_ oldal.
- Legyenek színekkel megkülönbözhetőek az egyes események
- Maradjon meg a keresés rész, a táblázat csak a kiválasztott tárgy eseményeit mutassa.

**Comment by krkskmate** [comment]
Színes táblázat kész, alignment bugok javítása szükséges.

**Comment by krkskmate** [comment]
Minden is ki lett javítva
