### ISSUE TITLE
Projektek - takeout

### ISSUE THREAD

**Issue by krkskmate** [gutasiadam/mediaio#164]
Nem tudom pontosan mit szeretne matu de projekthez valamilyen eszközkövetést hozzá kellene adni.

A kivett eszközöknek lehetne egy olyan oszlop az adatbázisban amiben benne van a projekt ID és úgy könnyű lenne őket összelinkelni is akár!

**Comment by foldesa** [comment]
ezt addig vissza lehet rakni a fiókba amíg az előjegyezhető dolog nem működik
(és utána sem biztos, hogy kell)

**Comment by foldesa** [comment]
Az előjegyezhető kivétel kb megoldja ezt.
