### ISSUE TITLE
Előjegyezhető kivitelek

### ISSUE THREAD

**Issue by gutasiadam** [gutasiadam/mediaio#89]
Legyen lehetőség előjegyezni tárgyakat, amiket később ki szeretnénk vinni

**Comment by gutasiadam** [comment]
Legutóbbi megbeszélésen felvetett ötletek:

- [ ] Értesítés az egy héten belüli előjegyzés esetén annak a felhasználónak, aki előjegyzett.

Lenne egy külön gomb az előjegyzésre a jelenlegi takeout oldalon?

- Szintén le kellene Ackolnia valakinek? - **IGEN**
    - [x] Kivegye-e automatán?? - Nem 
    - [x] Csak az adott felhasználó tudná kivenni a tárgyat, akinek elő van jegyezve abban az idősávban
- [x] Automatikusan leveszi az előjegyzést arról, amit nem vettél ki
- [x] és az automata másnap leveszi az előjegyzéseket, ha egyetlen tárgyat sem vettél ki végül az előjegyzésedből

Ezek még változhatnak, csak irányadó a megoldáshoz

**Comment by krkskmate** [comment]
Plan szerkesztés:
- [x] Időtartam kiírása
- [x] Lehessen itemeket kivenni belőle
- [x] Lehessen itemeket hozzáadni
- [x] Lehessen időtartamot módosítani
![image](https://github.com/gutasiadam/mediaio/assets/75211897/12caa3dc-9327-4255-b95f-96b53407d894)
---
Original Takeout: 
- [x] A kint levő tárgyak is legyenek elérhetőek (ha a role engedi) --> lehessen velük tervezni
...
---
Értesítési rendszer: (email)
- [x] Lejárat előtt 1 nappal
- [x] Lejáratkor
- [x] Kezdet előtt 1? nappal
....
---
Automatizált rész (CRON jobokkal?!):
- [x] 1 napon belül nem elindított plan state -1-be állítása, itemek elérhetővé tétele
Egyelőre ennyi?! Minden reggel 6-kor lefutó teszt
